# Generated by Django 3.2.23 on 2024-12-05 09:17

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BoundingBox',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coordinates', django.contrib.gis.db.models.fields.PolygonField(srid=4326)),
            ],
        ),
        migrations.CreateModel(
            name='Feature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('geometry', django.contrib.gis.db.models.fields.LineStringField(srid=4326)),
                ('bbox', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='routing.boundingbox')),
            ],
        ),
        migrations.CreateModel(
            name='FeatureSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('distance', models.FloatField()),
                ('duration', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Metadata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attribution', models.CharField(max_length=255)),
                ('service', models.CharField(max_length=255)),
                ('timestamp', models.BigIntegerField()),
                ('query', models.JSONField()),
                ('engine', models.JSONField()),
            ],
        ),
        migrations.CreateModel(
            name='Route',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_location', django.contrib.gis.db.models.fields.PointField(srid=4326)),
                ('end_location', django.contrib.gis.db.models.fields.PointField(srid=4326)),
            ],
        ),
        migrations.CreateModel(
            name='Segment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('distance', models.FloatField()),
                ('duration', models.FloatField()),
                ('feature', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='routing.feature')),
            ],
        ),
        migrations.CreateModel(
            name='WayPoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coordinate', django.contrib.gis.db.models.fields.PointField(srid=4326)),
            ],
        ),
        migrations.CreateModel(
            name='Step',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('distance', models.FloatField()),
                ('duration', models.FloatField()),
                ('instruction', models.CharField(max_length=255)),
                ('type', models.SmallIntegerField(choices=[(0, 'Left'), (1, 'Right'), (2, 'Sharp left'), (3, 'Sharp right'), (4, 'Slight left'), (5, 'Slight right'), (6, 'Straight'), (7, 'Enter roundabout'), (8, 'Exit roundabout'), (9, 'U-turn'), (10, 'Goal'), (11, 'Depart'), (12, 'Keep left'), (13, 'Keep right')])),
                ('name', models.CharField(max_length=255)),
                ('segment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='routing.segment')),
                ('way_points', models.ManyToManyField(to='routing.WayPoint')),
            ],
        ),
        migrations.CreateModel(
            name='GeoJsonFeatureCollection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bbox', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='routing.boundingbox')),
                ('metadata', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='routing.metadata')),
            ],
        ),
        migrations.AddField(
            model_name='feature',
            name='feature_collection',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='routing.geojsonfeaturecollection'),
        ),
        migrations.AddField(
            model_name='feature',
            name='summary',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='routing.featuresummary'),
        ),
        migrations.AddField(
            model_name='feature',
            name='way_points',
            field=models.ManyToManyField(to='routing.WayPoint'),
        ),
    ]
