# Generated by Django 3.2.23 on 2024-12-05 09:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('routing', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='GeoJsonFeatureCollection',
            new_name='FeatureCollection',
        ),
    ]
