# Generated by Django 3.2.23 on 2024-12-06 21:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('routing', '0006_auto_20241206_2138'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='city',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='city',
            name='longitude',
        ),
    ]
