# Generated by Django 3.2.23 on 2024-12-06 22:23

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('routing', '0007_auto_20241206_2153'),
    ]

    operations = [
        migrations.AlterField(
            model_name='truckstop',
            name='coordinate',
            field=django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326),
        ),
    ]
