# Generated by Django 3.2.23 on 2024-12-07 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('routing', '0009_alter_city_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='city',
            name='state',
            field=models.IntegerField(choices=[(1, 'AL'), (2, 'AK'), (3, 'AZ'), (4, 'AR'), (5, 'CA'), (6, 'CO'), (7, 'CT'), (8, 'DE'), (9, 'FL'), (10, 'GA'), (11, 'HI'), (12, 'ID'), (13, 'IL'), (14, 'IN'), (15, 'IA'), (16, 'KS'), (17, 'KY'), (18, 'LA'), (19, 'ME'), (20, 'MD'), (21, 'MA'), (22, 'MI'), (23, 'MN'), (24, 'MS'), (25, 'MO'), (26, 'MT'), (27, 'NE'), (28, 'NV'), (29, 'NH'), (30, 'NJ'), (31, 'NM'), (32, 'NY'), (33, 'NC'), (34, 'ND'), (35, 'OH'), (36, 'OK'), (37, 'OR'), (38, 'PA'), (39, 'RI'), (40, 'SC'), (41, 'SD'), (42, 'TN'), (43, 'TX'), (44, 'UT'), (45, 'VT'), (46, 'VA'), (47, 'WA'), (48, 'WV'), (49, 'WI'), (50, 'WY'), (51, 'AB'), (52, 'BC'), (53, 'MB'), (54, 'NB'), (55, 'NL'), (56, 'NS'), (57, 'ON'), (58, 'PE'), (59, 'QC'), (60, 'SK'), (61, 'YT')]),
        ),
        migrations.AlterField(
            model_name='truckstop',
            name='fuel_retail_price',
            field=models.DecimalField(decimal_places=12, max_digits=24),
        ),
        migrations.AlterField(
            model_name='truckstop',
            name='state',
            field=models.SmallIntegerField(choices=[(1, 'AL'), (2, 'AK'), (3, 'AZ'), (4, 'AR'), (5, 'CA'), (6, 'CO'), (7, 'CT'), (8, 'DE'), (9, 'FL'), (10, 'GA'), (11, 'HI'), (12, 'ID'), (13, 'IL'), (14, 'IN'), (15, 'IA'), (16, 'KS'), (17, 'KY'), (18, 'LA'), (19, 'ME'), (20, 'MD'), (21, 'MA'), (22, 'MI'), (23, 'MN'), (24, 'MS'), (25, 'MO'), (26, 'MT'), (27, 'NE'), (28, 'NV'), (29, 'NH'), (30, 'NJ'), (31, 'NM'), (32, 'NY'), (33, 'NC'), (34, 'ND'), (35, 'OH'), (36, 'OK'), (37, 'OR'), (38, 'PA'), (39, 'RI'), (40, 'SC'), (41, 'SD'), (42, 'TN'), (43, 'TX'), (44, 'UT'), (45, 'VT'), (46, 'VA'), (47, 'WA'), (48, 'WV'), (49, 'WI'), (50, 'WY'), (51, 'AB'), (52, 'BC'), (53, 'MB'), (54, 'NB'), (55, 'NL'), (56, 'NS'), (57, 'ON'), (58, 'PE'), (59, 'QC'), (60, 'SK'), (61, 'YT')]),
        ),
    ]
