# Generated by Django 3.2.23 on 2024-12-07 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('routing', '0010_auto_20241207_0600'),
    ]

    operations = [
        migrations.AddField(
            model_name='route',
            name='fuel_stops',
            field=models.ManyToManyField(to='routing.TruckStop'),
        ),
        migrations.AddField(
            model_name='route',
            name='total_fuel_spend',
            field=models.DecimalField(decimal_places=12, default=0.0, max_digits=24),
            preserve_default=False,
        ),
    ]
