# Generated by Django 3.2.23 on 2024-12-07 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('routing', '0011_auto_20241207_0709'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='city',
            index=models.Index(db_tablespace='pg_default', fields=['location'], name='location_idx'),
        ),
    ]
